version: '3.7'
services:
  client:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - "db-data:/data"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"


volumes:
  db-data:
