version: '3.7'
services:

  client:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - "db-data:/data"

  prometheus:
    image: tantalic/armv7-prometheus:v1.5.1
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/:/etc/prometheus/"
      - "prometheus-data:/prometheus"
    depends_on:
      - cadvisor

  cadvisor:
    image: harveyr/cadvisor-arm
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  grafana:
    image: raymondmm/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always

volumes:
  db-data:
  prometheus-data:
  grafana-data:
